/**
 * Seed data: Top KOL (Key Opinion Leader) wallets from kolscan.io
 * These populate the initial SolCity so there's a city to explore on launch.
 */

export interface KolWallet {
  address: string;
  name: string;
  rank: number;
}

export const KOL_WALLETS: KolWallet[] = [
  // ── kolscan.io/leaderboard (top 50, March 2026) ──
  { rank: 1,  name: "Cented",            address: "CyaE1VxvBrahnPWkqm5VsdCvyS2QmNht2UFrKJHga54o" },
  { rank: 2,  name: "clukz",             address: "G6fUXjMKPJzCY1rveAE6Qm7wy5U3vZgKDJmN1VPAdiZC" },
  { rank: 3,  name: "Solstice",          address: "GrD2umbfEBjQKFPDQvmmYNQ5eyRL9SAdWJj9FFMyeaDN" },
  { rank: 4,  name: "decu",              address: "4vw54BmAogeRV3vPKWyFet5yf8DTLcREzdSzx4rw9Ud9" },
  { rank: 5,  name: "Jijo",              address: "4BdKaxN8G6ka4GYtQQWk4G4dZRUTX2vQH9GcXdBREFUk" },
  { rank: 6,  name: "Smokez",            address: "5t9xBNuDdGTGpjaPTx6hKd7sdRJbvtKS8Mhq6qVbo8Qz" },
  { rank: 7,  name: "Pain",              address: "J6TDXvarvpBdPXTaTU8eJbtso1PUCYKGkVtMKUUY8iEa" },
  { rank: 8,  name: "Trenchman",         address: "Hw5UKBU5k3YudnGwaykj5E8cYUidNMPuEewRRar5Xoc7" },
  { rank: 9,  name: "Otta",              address: "As7HjL7dzzvbRbaD3WCun47robib2kmAKRXMvjHkSMB5" },
  { rank: 10, name: "MAMBA",             address: "4nvNc7dDEqKKLM4Sr9Kgk3t1of6f8G66kT64VoC95LYh" },
  { rank: 11, name: "Sheep",             address: "78N177fzNJpp8pG49xDv1efYcTMSzo9tPTKEA9mAVkh2" },
  { rank: 12, name: "juicyfruity",       address: "Cv4JVc25RZ7JV8HhEXrnxJjzebMBCqN5prB5ec43aJSz" },
  { rank: 13, name: "fz7",               address: "G2mgnzpr59vYjKpwU9q5zVfS9yQ9HezMwjuqF7LACvR4" },
  { rank: 14, name: "radiance",          address: "FAicXNV5FVqtfbpn4Zccs71XcfGeyxBSGbqLDyDJZjke" },
  { rank: 15, name: "Letterbomb",        address: "BtMBMPkoNbnLF9Xn552guQq528KKXcsNBNNBre3oaQtr" },
  { rank: 16, name: "West",              address: "JDd3hy3gQn2V982mi1zqhNqUw1GfV2UL6g76STojCJPN" },
  { rank: 17, name: "Ban",               address: "8DGbkGgQewL9mx4aXzZCUChr7hBVXvPK9fYqSqc7Ajpn" },
  { rank: 18, name: "slingoor",          address: "6mWEJG9LoRdto8TwTdZxmnJpkXpTsEerizcGiCNZvzXd" },
  { rank: 19, name: "Zil",               address: "FSAmbD6jm6SZZQadSJeC1paX3oTtAiY9hTx1UYzVoXqj" },
  { rank: 20, name: "Qavec",             address: "gangJEP5geDHjPVRhDS5dTF5e6GtRvtNogMEEVs91RV" },
  { rank: 21, name: "Limfork.eth",       address: "BQVz7fQ1WsQmSTMY3umdPEPPTm1sdcBcX9sP7o6kPRmB" },
  { rank: 22, name: "JADAWGS",           address: "3H9LVHarjBoZ2YPEsgFbVD1zuERCGwfp4AeyHoHsFSEC" },
  { rank: 23, name: "jamessmith",        address: "EQaxqKT3N981QBmdSUGNzAGK5S26zUwAdRHhBCgn87zD" },
  { rank: 24, name: "kreo",              address: "BCnqsPEtA1TkgednYEebRpkmwFRJDCjMQcKZMMtEdArc" },
  { rank: 25, name: "Latuche",           address: "GJA1HEbxGnqBhBifH9uQauzXSB53to5rhDrzmKxhSU65" },
  { rank: 26, name: "Ramset",            address: "71PCu3E4JP5RDBoY6wJteqzxkKNXLyE1byg5BTAL9UtQ" },
  { rank: 27, name: "Walta",             address: "39q2g5tTQn9n7KnuapzwS2smSx3NGYqBoea11tBjsGEt" },
  { rank: 28, name: "Kadenox",           address: "B32QbbdDAyhvUQzjcaM5j6ZVKwjCxAwGH5Xgvb9SJqnC" },
  { rank: 29, name: "Pandora",           address: "UxuuMeyX2pZPHmGZ2w3Q8MysvExCAquMtvEfqp2etvm" },
  { rank: 30, name: "jakey",             address: "B3JyPD3t9ufZWfL3namyvoc258KH74JojSxxurUg9jCT" },
  { rank: 31, name: "dov 7",             address: "8nqtxpFpuXwfXG4pBLsDkkuMMPK9FjSkBMCn542HiM3v" },
  { rank: 32, name: "Naruza",            address: "ASVzakePP6GNg9r95d4LPZHJDMXun6L6E4um4pu5ybJk" },
  { rank: 33, name: "Hesi",              address: "FpD6n8gfoZNxyAN6QqNH4TFQdV9vZEgcv5W4H2YL8k4X" },
  { rank: 34, name: "gr3g",              address: "J23qr98GjGJJqKq9CBEnyRhHbmkaVxtTJNNxKu597wsA" },
  { rank: 35, name: "Putrick",           address: "AVjEtg2ECYKXYeqdRQXvaaAZBjfTjYuSMTR4WLhKoeQN" },
  { rank: 36, name: "k4ye",              address: "5fHJszey2UdB2nETS1y6NS2wSG4ic9byKtbgJzaYzGeV" },
  { rank: 37, name: "Al4n",              address: "2YJbcB9G8wePrpVBcT31o8JEed6L3abgyCjt5qkJMymV" },
  { rank: 38, name: "Eddy",              address: "DuGezKLZp8UL2aQMHthoUibEC7WSbpNiKFJLTtK1QHjx" },
  { rank: 39, name: "big bags bobby",    address: "8oQoMhfBQnRspn7QtNAq2aPThRE4q94kLSTwaaFQvRgs" },
  { rank: 40, name: "Betman",            address: "BoYHJoKntk3pjkaV8qFojEonSPWmWMfQocZTwDd1bcGG" },
  { rank: 41, name: "CookDoc",           address: "Dvbv5TdAyPpJk16X9mUxWFVicYtCUxTLhuof8TGuUaRv" },
  { rank: 42, name: "Kev",               address: "BTf4A2exGK9BCVDNzy65b9dUzXgMqB4weVkvTMFQsadd" },
  { rank: 43, name: "CoCo",              address: "FqojC24nUn3x6oMQC2ypBHmtH7rFAnKS6DvwsJoCMaiv" },
  { rank: 44, name: "chester",           address: "PMJA8UQDyWTFw2Smhyp9jGA6aTaP7jKHR7BPudrgyYN" },
  { rank: 45, name: "Damian Prosalendis",address: "AEeJUPCiGR3yCoukTh1G58o4LYsUEyzrXtfmfMc2kJMX" },
  { rank: 46, name: "xunle",             address: "4YzpSZpxDdjNf3unjkCtdWEsz2FL5mok7e5XQaDNqry8" },
  { rank: 47, name: "sadizmed",          address: "DTdHa4auX68jFtXv9wkzMYCahg295AnRuwvm6moW6meZ" },
  { rank: 48, name: "theo",              address: "Bi4rd5FH5bYEN8scZ7wevxNZyNmKHdaBcvewdPFxYdLt" },
  { rank: 49, name: "Solana degen",      address: "9tY7u1HgEt2RDcxym3RJ9sfvT3aZStiiUwXd44X9RUr8" },
  { rank: 50, name: "LJC",               address: "6HJetMbdHBuk3mLUainxAPpBpWzDgYbHGTS2TqDAUSX2" },
  // ── additional known KOLs from previous data ──
  { rank: 51, name: "Cowboy",            address: "6EDaVsS6enYgJ81tmhEkiKFcb4HuzPUVFZeom6PHUqN3" },
  { rank: 52, name: "Scharo",            address: "4sAUSQFdvWRBxR8UoLBYbw8CcXuwXWxnN8pXa4mtm5nU" },
  { rank: 53, name: "Cooker",            address: "8deJ9xeUvXSJwicYptA9mHsU2rN2pDx37KWzkDkEXhU6" },
  { rank: 54, name: "bandit",            address: "5B79fMkcFeRTiwm7ehsZsFiKsC7m7n1Bgv9yLxPp9q2X" },
  { rank: 55, name: "Sebastian",         address: "3BLjRcxWGtR7WRshJ3hL25U3RjWr5Ud98wMcczQqk4Ei" },
  { rank: 56, name: "Paper",             address: "FwjYcbfktK8PC2bzCrqxR6QkUPxmHFbcFGNrz3YAV7ft" },
  { rank: 57, name: "Silver",            address: "67Nwfi9hgwqhxGoovT2JGLU67uxfomLwQAWncjXXzU6U" },
  { rank: 58, name: "storm",             address: "Dxudj2DQ5odnqgZvUocaeWc1eYC78Q8vfmVtPpvTrRNh" },
  { rank: 59, name: "Johnson",           address: "J9TYAsWWidbrcZybmLSfrLzryANf4CgJBLdvwdGuC8MB" },
  { rank: 60, name: "sarah milady",      address: "AAMnoNo3TpezKcT7ah9puLFZ4D59muEhQHJJqpX16ccg" },
  { rank: 61, name: "dv",                address: "BCagckXeMChUKrHEd6fKFA1uiWDtcmCXMsqaheLiUPJd" },
  { rank: 62, name: "Frags",             address: "2yoJibiZUGB1gs31gvtynRTyx9vmj8VrWoQvXDDzUFHS" },
  { rank: 63, name: "Xanse",             address: "B9K2wTQcRDLRLhMKFyRh2hPqHrr6VKiCC9yNGpkMUXrh" },
  { rank: 64, name: "Giann",             address: "GNrmKZCxYyNiSUsjduwwPJzhed3LATjciiKVuSGrsHEC" },
  { rank: 65, name: "Fizzwick",          address: "3pcmVZ1DwKbqnjbGbeg3FycThT1AkTpGQYB96jGU6oS1" },
  { rank: 66, name: "kitty",             address: "qP3Q8d4WWsGbqkTfyA9Dr6cAD7DQoBuxPJMFTK48rWU" },
  { rank: 67, name: "Cupsey",            address: "2fg5QD1eD7rzNNCsvnhmXFm5hqNgwTTG8p7kQ6f3rx6f" },
  { rank: 68, name: "nad",               address: "363sqMFaxZgvCoGzxKjXe1BqMGYkSVoCwmghZUndXuaT" },
  { rank: 69, name: "Dex",               address: "mW4PZB45isHmnjGkLpJvjKBzVS5NXzTJ8UDyug4gTsM" },
  { rank: 70, name: "Zef",               address: "EjtQrPTbcMevStBkpnjsH23NfUCMhGHusTYsHuGVQZp2" },
  { rank: 71, name: "cap",               address: "CAPn1yH4oSywsxGU456jfgTrSSUidf9jgeAnHceNUJdw" },
  { rank: 72, name: "dyor",              address: "AVmFMbuehLbCWB6sPdZGComwyrHtxJETZVktdA65j3Gq" },
  { rank: 73, name: "Qtdegen",           address: "7tiRXPM4wwBMRMYzmywRAE6jveS3gDbNyxgRrEoU6RLA" },
  { rank: 74, name: "Bastille",          address: "3kebnKw7cPdSkLRfiMEALyZJGZ4wdiSRvmoN4rD1yPzV" },
  // ── SolCity project wallet ──
  { rank: 75, name: "SolCity",           address: "CYuayvLTYnbARMqcKM8CzKbRaqCkMri9iewBpGfUPsE6" },
];
